use crate::runtime::Span;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

/// One piece of an interpolated string literal.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InterpolationSegment {
    /// Literal text, with `{{` and `}}` already reduced to `{` and `}`.
    Literal(String),
    /// A `{expression[,alignment][:format]}` hole. The source text is parsed
    /// later, by the parser, so the scanner stays free of expression grammar.
    Hole {
        source: String,
        alignment: Option<i32>,
        format: Option<String>,
        span: Span,
    },
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TokenKind {
    Identifier(String, Option<crate::frontend::type_model::TypeName>),
    String(String),
    /// An interpolated string literal, `$"total: {count}"`, already split into
    /// its literal and hole segments by the scanner.
    InterpolatedString(Vec<InterpolationSegment>),
    Integer(i64),
    Float(String),
    Sub,
    Function,
    Iterator,
    Imports,
    Namespace,
    Module,
    Const,
    Option,
    Explicit,
    Base,
    Compare,
    Binary,
    Text,
    Version,
    Begin,
    Type,
    Structure,
    Interface,
    Enum,
    Class,
    Inherits,
    MustInherit,
    NotInheritable,
    Implements,
    Shared,
    ReadOnly,
    WriteOnly,
    Delegate,
    Overloads,
    Overridable,
    Overrides,
    MustOverride,
    Shadows,
    Event,
    Declare,
    Lib,
    Alias,
    Any,
    RaiseEvent,
    WithEvents,
    Property,
    Default,
    Get,
    Let,
    Call,
    Set,
    Nothing,
    AddressOf,
    Empty,
    Null,
    Is,
    IsNot,
    Like,
    TypeOf,
    New,
    Me,
    MyBase,
    MyClass,
    Public,
    Private,
    Friend,
    Protected,
    End,
    Dim,
    As,
    AddHandler,
    RemoveHandler,
    Async,
    Await,
    ByVal,
    ByRef,
    Optional,
    ParamArray,
    Static,
    Partial,
    Return,
    StringType,
    IntegerType,
    BooleanType,
    VariantType,
    True,
    False,
    If,
    Then,
    Else,
    ElseIf,
    Select,
    Case,
    While,
    Wend,
    With,
    Using,
    Do,
    Loop,
    Until,
    For,
    From,
    GoTo,
    Each,
    In,
    Of,
    To,
    Step,
    Next,
    Exit,
    Continue,
    On,
    Error,
    Resume,
    Try,
    Catch,
    Finally,
    Throw,
    Yield,
    And,
    AndAlso,
    Or,
    OrElse,
    Xor,
    Eqv,
    Imp,
    Not,
    Mod,
    ReDim,
    Preserve,
    Erase,
    LSet,
    RSet,
    Collection,
    Operator,
    Console,
    WriteLine,
    Hex(String),
    Octal(String),
    Dot,
    Comma,
    Colon,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Plus,
    Minus,
    Star,
    Caret,
    Slash,
    Backslash,
    Ampersand,
    Percent,
    Exclamation,
    Question,
    Hash,
    At,
    Dollar,
    Semicolon,
    Equal,
    NotEqual,
    ShiftLeft,
    ShiftRight,
    PlusEqual,
    MinusEqual,
    StarEqual,
    SlashEqual,
    BackslashEqual,
    CaretEqual,
    AmpersandEqual,
    ShiftLeftEqual,
    ShiftRightEqual,
    Less,
    Greater,
    LessEqual,
    GreaterEqual,
    Newline,
    Eof,
}
