name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:

          # Linux x64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            archive: valo-linux-x64.tar.gz
            binary: valo

          # Linux x86
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            archive: valo-linux-x86.tar.gz
            binary: valo

          # Windows x64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            archive: valo-windows-x64.zip
            binary: valo.exe

          # Windows x86
          - os: windows-latest
            target: i686-pc-windows-msvc
            archive: valo-windows-x86.zip
            binary: valo.exe

          # macOS ARM64
          - os: macos-latest
            target: aarch64-apple-darwin
            archive: valo-macos-arm64.tar.gz
            binary: valo

          # macOS x64
          - os: macos-latest
            target: x86_64-apple-darwin
            archive: valo-macos-x64.tar.gz
            binary: valo

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package Unix
        if: runner.os != 'Windows'
        shell: bash
        run: |
          mkdir release

          cp target/${{ matrix.target }}/release/${{ matrix.binary }} release/${{ matrix.binary }}

          tar -czf ${{ matrix.archive }} -C release ${{ matrix.binary }}

      - name: Package Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          mkdir release

          copy target\${{ matrix.target }}\release\${{ matrix.binary }} release\${{ matrix.binary }}

          Compress-Archive `
            -Path release\${{ matrix.binary }} `
            -DestinationPath ${{ matrix.archive }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
            *.zip
